useGroupedVersion: true

version_info_list_desktop:
  - value: latest version
  - value: 2.x
    child:
      - 2.6.1000_cplusplus
      - 2.5.2100_python
      - 2.4.2100_python
      - 2.4.2000_dotnet
      - 2.4.2000_python
      - 2.4.2000_cplusplus

